export const constants = (key) => process.env[`REACT_APP_${key}`];
export const headerArr = [
  { key: "ID", value: "id" },
  { key: "Name", value: "name" },
  { key: "Email", value: "email" },
  { key: "Birth Date", value: "birth_date" },
  { key: "Position Applied", value: "position_applied" },
  { key: "Year Of Experience", value: "year_of_experience" },
  { key: "Application Date", value: "application_date" },
  { key: "Status", value: "status" },
];

export const mockData = [
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 1,
    name: "Alvin Satterfield",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 2,
    name: "Colette Morar",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 3,
    name: "Three",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 4,
    name: "Four",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 5,
    name: "Five",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 6,
    name: "Six",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 7,
    name: "Seven",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 8,
    name: "Eight",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 9,
    name: "Nine",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 10,
    name: "Ten",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
  {
    application_date: "2018-07-02",
    birth_date: "1997-09-07",
    email: "cornellbartell@connellyleannon.biz",
    id: 11,
    name: "Eleven",
    position_applied: "Technician",
    status: "rejected",
    year_of_experience: 5,
  },
  {
    application_date: "2017-11-18",
    birth_date: "1998-08-03",
    email: "corinnestark@pacocha.co",
    id: 12,
    name: "Tweleve",
    position_applied: "Designer",
    status: "waiting",
    year_of_experience: 3,
  },
];
